name: Auto merge Dependabot PRs

on:
    pull_request:

jobs:
    auto-approve:
        name: Auto approve
        runs-on: ubuntu-latest
        steps:
            - uses: hmarr/auto-approve-action@v2.0.0
              if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"
    auto-merge:
      name: Auto merge
      runs-on: ubuntu-latest
      needs: auto-approve
      steps:
        - uses: actions/checkout@v2
        - uses: ahmadnassri/action-dependabot-auto-merge@v2
          with:
            target: minor
            github-token: "${{ secrets.GITHUB_TOKEN }}"
