name: Auto merge Dependabot PRs

on:
    pull_request:

jobs:
    auto-approve:
        name: Auto approve
        runs-on: ubuntu-latest
        steps:
            - uses: hmarr/auto-approve-action@v2.0.0
              if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"
    auto-merge:
        name: Auto merge after successful checks
        needs: auto-approve
        runs-on: ubuntu-latest
        steps:
            - name: Auto merge
                # Custom action for auto merging already available on marketplace
              uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
                # Perform the auto merge action only when the PR is raised by dependabot
              if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
              with:
                github-token: "${{ secrets.GITHUB_TOKEN }}"
